### ISSUE TITLE
ModuleNotFoundError: No module named 'habana_frameworks.torch.hpu'

### ISSUE THREAD

**Issue by sameeravithana** [philschmid/deep-learning-habana-huggingface#3]
Have an import error when initializing GaudiTrainingArguments in the text-classification.ipynb.

**Comment by sameeravithana** [comment]
This is due to the updated optimum-habana lib. It can be resolved by latest docker. Might be good to provide instructions to move with the latest docker in your tutorial.

`docker run -ti --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --net=host --ipc=host -v $(pwd):/home/ubuntu/dev --workdir=/home/ubuntu/dev vault.habana.ai/gaudi-docker/1.6.0/ubuntu20.04/habanalabs/pytorch-installer-1.12.0`

**Comment by philschmid** [comment]
Thank you @sameeravithana updated. The notebook and my blog posts. BTW we also have ready to use `habana-optimum` container. https://hub.docker.com/r/huggingface/optimum-habana/tags
```bash
huggingface/optimum-habana:4.21.1-pt1.11.0-synapse1.5.0
```
